(() => {
  const t = (term, pattern, meaning, contexts, evidence, ambiguity = "", flags = "i") => ({
    term,
    pattern,
    meaning,
    contexts,
    evidence,
    ambiguity,
    flags,
  });
  const biz = (startup, finance = startup) => ({ startup, finance });
  const prod = (product, startup = product) => ({ product, startup });
  const sales = (startup, career = startup) => ({ startup, career });
  const tech = (product, startup = product) => ({ engineering: product, product, startup });
  const work = (career, product = career) => ({ career, product });

  window.LINGUA_CUE_EXTRA_TERMS = [
    t("AI", String.raw`\bAI\b|artificial intelligence`, "Artificial Intelligence，人工智能。", tech("产品、自动化、数据分析、搜索、客服和内容生成场景都常见。", "AI 创业项目里要继续区分传统 ML、LLM、agent 或 workflow。"), ["LLM", "ML", "model", "人工智能", "自动化", "模型"], "通常较明确；如果对方在讲具体技术，可能还需要区分传统 AI、ML 或 LLM。"),
    t("ML", String.raw`\bML\b|machine learning`, "Machine Learning，机器学习。", tech("通过数据训练模型来做预测、分类、推荐或生成。", "AI 团队会围绕数据、模型、部署和评测讨论 ML。"), ["data", "model", "prediction", "机器学习", "训练", "模型"]),
    t("LLM", String.raw`\bLLM\b|large language model`, "Large Language Model，大语言模型。", tech("AI 产品、自动化、客服、搜索和内容生成场景里常见。", "创业项目里常和 RAG、agent、prompt、eval、成本和延迟一起出现。"), ["AI", "RAG", "prompt", "模型", "大语言模型", "生成"], "也可能是法学硕士 LL.M.，需看上下文。"),
    t("RAG", String.raw`\bRAG\b|retrieval augmented generation`, "Retrieval-Augmented Generation，先检索资料再让模型生成答案。", tech("常用于把公司文档、知识库或数据库接进 AI 回答流程。", "企业 AI 应用会用 RAG 提高可追溯性并降低幻觉。"), ["retrieval", "knowledge", "vector", "search", "检索", "知识库", "向量"]),

    t("SAM", String.raw`\bSAM\b|serviceable available market`, "Serviceable Available Market，当前产品和渠道实际能服务到的市场规模。", biz("常和 TAM、SOM 一起出现，用来把大市场收窄到可执行范围。", "投资人会用 SAM 判断短中期可达收入空间。"), ["TAM", "SOM", "market", "segment", "市场", "细分", "规模"]),
    t("SOM", String.raw`\bSOM\b|serviceable obtainable market`, "Serviceable Obtainable Market，在可服务市场里更现实能拿下的份额。", biz("适合聊早期切入市场和第一批可赢客户。", "融资材料里常用它解释短期增长目标是否可信。"), ["TAM", "SAM", "share", "market", "份额", "短期", "切入"]),
    t("ACV", String.raw`\bACV\b|annual contract value`, "Annual Contract Value，单个客户合同折算到一年的合同价值。", biz("B2B SaaS 会用 ACV 区分 SMB、中型企业和 Enterprise 客户。", "ACV 影响销售周期、CAC payback 和收入质量判断。"), ["contract", "enterprise", "deal", "合同", "客单价", "销售周期"]),
    t("TCV", String.raw`\bTCV\b|total contract value`, "Total Contract Value，整个合同周期的总合同价值。", biz("如果客户签多年，TCV 会高于单年 ACV。", "看合同价值时要区分 TCV、ACV 和真实可确认收入。"), ["contract", "multi-year", "ACV", "合同", "多年", "总额"]),
    t("ARPU", String.raw`\bARPU\b|average revenue per user`, "Average Revenue Per User，平均每个用户带来的收入。", prod("产品和增长会看 ARPU 是否随定价、使用深度或用户质量变化。", "常用于订阅、消费产品和平台型产品的收入拆解。"), ["revenue", "user", "pricing", "收入", "用户", "定价"]),
    t("ARPA", String.raw`\bARPA\b|average revenue per account`, "Average Revenue Per Account，平均每个账户或客户带来的收入。", biz("B2B 场景常比 ARPU 更有意义，因为一个 account 里可能有多个 seat。", "可用来观察客户结构是否向更大账户迁移。"), ["account", "revenue", "seat", "账户", "客户", "收入"]),
    t("GMV", String.raw`\bGMV\b|gross merchandise value`, "Gross Merchandise Value，平台上完成交易的商品或服务总额。", biz("Marketplace 和交易平台常看 GMV，但它不等于收入。", "估值时会继续看 take rate、毛利和净收入。"), ["marketplace", "transaction", "take rate", "平台", "交易", "流水"]),
    t("Take Rate", String.raw`\btake rate\b|抽佣率|平台抽成`, "Take rate，平台从交易额中实际抽取为收入的比例。", biz("Marketplace、支付、广告和创作者平台常用这个指标。", "GMV 乘以 take rate 才更接近平台收入。"), ["GMV", "marketplace", "commission", "平台", "抽佣", "交易"]),
    t("Gross Margin", String.raw`\bgross margin\b|毛利率`, "Gross margin，毛利率，收入扣除直接成本后剩下的比例。", biz("SaaS 通常希望毛利率较高，AI 产品则会特别关注推理成本。", "投资人会用毛利率判断商业模式质量和扩张空间。"), ["margin", "COGS", "cost", "毛利", "成本", "云成本"]),
    t("COGS", String.raw`\bCOGS\b|cost of goods sold`, "Cost of Goods Sold，收入对应的直接成本。", biz("软件公司里可能包括云服务、模型推理、客服交付或第三方成本。", "COGS 会直接影响毛利率和单位经济模型。"), ["gross margin", "cost", "cloud", "成本", "毛利", "云服务"]),
    t("Burn Rate", String.raw`\bburn rate\b|burn\b(?=\s+(rate|multiple|cash))|烧钱速度|现金消耗`, "Burn rate，公司的现金消耗速度。", biz("早期公司会用它估算 runway 和下一轮融资压力。", "投资人会看 burn 是否换来了高质量增长。"), ["runway", "cash", "funding", "现金", "烧钱", "融资"]),
    t("Runway", String.raw`\brunway\b|现金跑道`, "Runway，按当前现金消耗速度还能撑多久。", biz("通常用月数表达，比如 12 months runway。", "融资讨论里会用它判断公司是否需要尽快融资或降本。"), ["burn", "cash", "month", "现金", "月", "融资"]),
    t("Burn Multiple", String.raw`\bburn multiple\b`, "Burn Multiple，每增加一单位净 ARR 消耗了多少现金。", biz("用来衡量增长效率，尤其适合 SaaS 公司。", "越低通常说明增长越有效率，但要结合阶段判断。"), ["ARR", "burn", "efficiency", "现金", "增长效率", "净新增"]),
    t("Rule of 40", String.raw`\brule of 40\b|40法则`, "Rule of 40，收入增长率加利润率约等于或超过 40% 的 SaaS 经验指标。", biz("更适合成熟 SaaS 公司，早期公司通常不机械套用。", "投资人会用它平衡增长和盈利质量。"), ["growth", "profit", "margin", "SaaS", "增长", "利润", "盈利"]),
    t("NRR", String.raw`\bNRR\b|net revenue retention`, "Net Revenue Retention，老客户收入净留存，和 NDR 很接近。", biz("包含续费、扩容、降级和流失后的净结果。", "高 NRR 表示客户会自然扩大使用和付费。"), ["retention", "expansion", "renewal", "churn", "留存", "续费", "扩容"]),
    t("GRR", String.raw`\bGRR\b|gross revenue retention`, "Gross Revenue Retention，老客户收入毛留存，不包含扩容带来的增量。", biz("用来观察客户是否稳定续费，和 NRR 搭配看更完整。", "GRR 能把真实流失情况和扩容增长分开看。"), ["retention", "renewal", "churn", "gross", "留存", "续费", "流失"]),
    t("Logo Retention", String.raw`\blogo retention\b|logo churn`, "Logo Retention，客户数量维度的留存，不按收入加权。", biz("适合判断客户是否还在，而不是他们花了多少钱。", "和 NRR、GRR 一起看可以区分客户流失和收入扩容。"), ["customer", "retention", "churn", "客户", "数量", "留存"]),
    t("CAC Payback", String.raw`\bCAC payback\b|payback period|回本周期`, "CAC Payback，获客成本需要多久通过毛利收回。", biz("B2B SaaS 常用它判断销售和市场投入是否健康。", "投资人会看 payback 是否随规模扩大而改善。"), ["CAC", "gross margin", "sales", "获客", "回本", "毛利"]),
    t("MoM", String.raw`\bMoM\b(?=\s*(growth|change|metric|数据|指标|增长|变化))|[Mm]onth[-\s]?over[-\s]?[Mm]onth|环比`, "Month-over-month，环比，和上一个月相比。", biz("早期增长常看 MoM，因为 YoY 数据还不稳定。", "看增长时要确认基数和季节性，避免被短期波动误导。"), ["growth", "month", "trend", "增长", "月", "环比"], "如果只是普通英文 mom，不应按指标理解。"),
    t("YoY", String.raw`\bYoY\b|[Yy]ear[-\s]?over[-\s]?[Yy]ear|同比`, "Year-over-year，同比，和去年同期相比。", biz("更适合有一定历史数据的业务。", "财务和市场数据常用 YoY 看长期趋势。"), ["growth", "year", "trend", "同比", "去年", "年度"], "", ""),
    t("QoQ", String.raw`\bQoQ\b|[Qq]uarter[-\s]?over[-\s]?[Qq]uarter|季环比`, "Quarter-over-quarter，和上一季度相比。", biz("SaaS 和上市公司财务讨论里常见。", "适合观察季度收入、利润和用户指标变化。"), ["quarter", "growth", "revenue", "季度", "环比", "收入"], "", ""),

    t("Pre-seed", String.raw`\bpre[-\s]?seed\b|种子前轮`, "Pre-seed，通常是非常早期的第一笔外部融资阶段。", biz("常用于验证创始团队、问题和早期原型。", "投资人关注创始人、洞察和初始验证，而不是完整收入。"), ["founder", "prototype", "funding", "创始人", "早期", "原型"]),
    t("Seed Round", String.raw`\bseed round\b|\bseed\b(?=\s+(round|funding|financing))|种子轮`, "Seed round，种子轮融资，通常用于验证产品和早期市场。", biz("常用于从原型走向 MVP、初始客户和小团队。", "投资人会看创始团队、市场、早期 traction 和融资用途。"), ["funding", "traction", "MVP", "融资", "种子轮", "早期"]),
    t("Series A", String.raw`\bseries\s+A\b|A轮`, "Series A，A 轮融资，通常意味着产品和市场已经有较强验证。", biz("A 轮后会更强调可重复增长、团队扩张和 GTM。", "投资人会看 revenue traction、留存、市场规模和增长效率。"), ["funding", "traction", "revenue", "A轮", "融资", "增长"]),
    t("Bridge Round", String.raw`\bbridge round\b|bridge financing|过桥轮`, "Bridge round，过桥融资，用来衔接下一轮融资或延长 runway。", biz("通常用于争取时间完成关键里程碑。", "需要关注条款、折扣、估值和是否说明下一轮压力。"), ["runway", "funding", "milestone", "过桥", "融资", "现金"]),
    t("SAFE", String.raw`\bSAFE\s+(note|round|financing|agreement)\b|simple agreement for future equity|SAFE协议`, "Simple Agreement for Future Equity，一种未来股权融资协议。", biz("早期融资常用，通常会涉及估值上限和折扣。", "需要看 cap、discount、MFN 等条款。"), ["cap", "discount", "equity", "估值上限", "折扣", "融资"]),
    t("Convertible Note", String.raw`\bconvertible note\b|可转债|可转换票据`, "Convertible Note，可转换票据，未来可能转换成股权的融资工具。", biz("早期公司可能用它快速融资。", "条款里会关注利息、到期日、估值上限和折扣。"), ["debt", "equity", "cap", "discount", "可转", "利息", "股权"]),
    t("Cap Table", String.raw`\bcap table\b|capitalization table|股权表`, "Cap table，股权结构表，展示股东、期权池和稀释情况。", biz("创始人和投资人会用它看每轮融资后的股权分布。", "DD 时会核对 cap table、期权池、SAFE 和可转债。"), ["equity", "dilution", "option pool", "股权", "稀释", "期权池"]),
    t("Dilution", String.raw`\bdilution\b|diluted\b|稀释`, "Dilution，股权稀释，新融资或期权池会降低原股东持股比例。", biz("融资时创始人会关注控制权和长期激励空间。", "估值、期权池和新投资额都会影响稀释比例。"), ["equity", "cap table", "option pool", "股权", "融资", "期权池"]),
    t("Term Sheet", String.raw`\bterm sheet\b|投资条款清单`, "Term sheet，投资条款清单，描述融资的主要商业和法律条款。", biz("拿到 term sheet 通常意味着融资谈判进入关键阶段。", "会关注估值、清算优先权、董事会席位、保护条款等。"), ["valuation", "liquidation", "board", "估值", "条款", "融资"]),
    t("Pro Rata", String.raw`\bpro rata\b|按比例跟投`, "Pro rata，按原持股比例继续跟投的权利。", biz("融资时老股东可能要求保留 pro rata 权利。", "VC 用它在后续轮次维持持股比例。"), ["follow-on", "investor", "ownership", "跟投", "持股", "比例"]),
    t("Lead Investor", String.raw`\blead investor\b|领投方|领投`, "Lead investor，领投方，通常主导条款、估值和尽调。", biz("创业者会先找能领投的投资人，再补充跟投。", "领投方通常承担更多 DD 和谈判工作。"), ["term sheet", "round", "DD", "领投", "融资", "条款"]),
    t("Angel Investor", String.raw`\bangel investor\b|angel round|天使投资人|天使轮`, "Angel investor，天使投资人，通常在非常早期提供资金和资源。", biz("常在 pre-seed 或 seed 前后出现。", "天使投资更依赖对创始人和方向的判断。"), ["founder", "early", "funding", "天使", "早期", "创始人"]),
    t("DD", String.raw`\bDD\b|due diligence|尽职调查|尽调`, "Due Diligence，尽职调查，投资或收购前对业务、财务、法律和技术的核查。", biz("融资进入后期时会被要求提供数据和材料。", "VC、PE、并购和投融资里高频出现。"), ["data room", "financial", "legal", "尽调", "财务", "法律"]),
    t("Data Room", String.raw`\bdata room\b|资料室|数据室`, "Data room，融资、尽调或并购时集中放材料的资料室。", biz("通常包含财务、合同、指标、团队、法务和产品材料。", "投资人会通过 data room 做 DD 和内部 memo。"), ["DD", "memo", "financial", "资料", "尽调", "合同"]),
    t("Valuation", String.raw`\bvaluation\b|估值`, "Valuation，估值，投资人和公司对公司价值的定价。", biz("会影响融资稀释、市场预期和下一轮压力。", "估值常由增长、收入质量、赛道、团队和市场环境共同决定。"), ["funding", "multiple", "revenue", "估值", "融资", "倍数"]),
    t("Pre-money", String.raw`\bpre[-\s]?money\b|投前估值`, "Pre-money，投前估值，即新资金进入前的公司估值。", biz("用来计算融资后创始人和投资人的持股比例。", "需要和 post-money 区分，否则会算错稀释。"), ["valuation", "post-money", "dilution", "投前", "估值", "稀释"]),
    t("Post-money", String.raw`\bpost[-\s]?money\b|投后估值`, "Post-money，投后估值，即投前估值加上新投资额。", biz("常用于计算融资完成后的股权比例。", "SAFE 和 priced round 里 post-money 表达会影响稀释理解。"), ["valuation", "pre-money", "dilution", "投后", "估值", "稀释"]),
    t("Board", String.raw`\bboard\b(?=\s+(seat|member|meeting|observer))|board seat|董事会`, "Board，董事会或董事会席位。", biz("融资后投资人可能拿 board seat 或 observer right。", "董事会结构会影响治理、重大事项和融资决策。"), ["investor", "governance", "seat", "董事会", "治理", "投资人"]),
    t("Option Pool", String.raw`\boption pool\b|期权池`, "Option pool，期权池，预留给员工激励的股权或期权额度。", biz("融资前后常会调整期权池，从而影响创始人稀释。", "投资条款里会明确期权池是否在投前计算。"), ["equity", "dilution", "employee", "期权池", "股权", "稀释"]),

    t("Activation", String.raw`\bactivation\b|激活率|用户激活`, "Activation，用户第一次体验到核心价值的过程或指标。", prod("增长团队会定义 activation event，比如完成首次关键操作。", "早期产品会通过 activation 判断用户是否真的 get 到价值。"), ["onboarding", "funnel", "event", "激活", "新用户", "漏斗"]),
    t("Onboarding", String.raw`\bonboarding\b|新手引导|入职引导`, "Onboarding，引导新人或新用户顺利开始使用。", prod("产品语境里通常指新用户激活路径。", "职场语境里也指新员工入职流程。"), ["activation", "new user", "training", "引导", "入职", "新用户"], "需要看上下文区分产品新手引导和员工入职。"),
    t("Retention", String.raw`\bretention\b|留存`, "Retention，留存，用户或客户持续回来使用或付费。", prod("产品团队会看 D1、D7、D30 或 cohort retention。", "留存是判断产品是否有长期价值的关键证据。"), ["cohort", "churn", "usage", "留存", "复购", "续费"]),
    t("Engagement", String.raw`\bengagement\b|参与度|活跃度`, "Engagement，参与度或活跃度，衡量用户使用产品的深度和频率。", prod("常和 DAU、MAU、session、核心行为一起看。", "早期产品可以用 engagement 判断是否有真实需求。"), ["DAU", "MAU", "usage", "活跃", "使用", "频率"]),
    t("Conversion", String.raw`\bconversion\b|conversion rate|转化率`, "Conversion，转化或转化率，用户从一个步骤进入下一个目标步骤。", prod("常用于注册、付费、试用、预约 demo 等漏斗。", "增长和销售会用转化率找瓶颈。"), ["funnel", "signup", "trial", "转化", "漏斗", "注册"]),
    t("Funnel", String.raw`\bfunnel\b|漏斗`, "Funnel，漏斗，用阶段化方式看用户或销售机会的流转。", prod("产品增长里常看曝光、点击、注册、激活、付费。", "销售里也可以指 lead 到 close 的 pipeline。"), ["conversion", "lead", "stage", "漏斗", "转化", "阶段"]),
    t("Cohort", String.raw`\bcohort\b|cohort analysis|分群|同期群`, "Cohort，同期群，把同一时间或同类用户放在一起分析。", prod("常用来观察留存、付费和行为随时间变化。", "收入和客户 cohort 可用于判断增长质量。"), ["retention", "analysis", "month", "留存", "分群", "同期"]),
    t("A/B Test", String.raw`\bA\/B test\b|\bAB test\b|split test|AB测试|A\/B测试`, "A/B Test，把用户分成不同版本来比较哪种方案更有效。", prod("产品增长中常用于验证按钮、文案、价格或流程变化。", "早期样本太小时要小心过度相信实验结果。"), ["experiment", "variant", "conversion", "实验", "对照", "转化"]),
    t("Experiment", String.raw`\bexperiment\b|实验`, "Experiment，实验，用可观察指标验证一个产品或增长假设。", prod("通常包含假设、指标、样本、实验组和结论。", "早期团队用实验降低方向不确定性。"), ["hypothesis", "metric", "variant", "假设", "指标", "样本"]),
    t("Feature Flag", String.raw`\bfeature flag\b|feature toggle|灰度开关`, "Feature flag，功能开关，用来控制某个功能是否对特定用户开放。", prod("常用于灰度发布、A/B test 和降低上线风险。", "小团队可以用它更快上线并保留回滚能力。"), ["rollout", "experiment", "release", "灰度", "开关", "发布"]),
    t("Roadmap", String.raw`\broadmap\b|路线图`, "Roadmap，路线图，产品或业务未来一段时间的优先级和计划。", prod("通常连接目标、用户问题、功能方向和资源安排。", "对外可能用于投资人或客户沟通，对内用于对齐团队。"), ["priority", "feature", "timeline", "路线图", "优先级", "计划"]),
    t("Backlog", String.raw`\bbacklog\b|需求池|积压任务`, "Backlog，待处理需求或任务池。", prod("产品和工程会从 backlog 里按优先级拉任务。", "项目讨论里可能指还没做完的一堆事项。"), ["sprint", "ticket", "priority", "需求池", "任务", "优先级"]),
    t("User Story", String.raw`\buser stor(y|ies)\b|用户故事`, "User story，用户故事，用用户视角描述需求和目标。", prod("常见格式是作为某类用户，我希望做某事，以便获得某种价值。", "产品面试里可能要求把需求拆成 user stories。"), ["requirement", "persona", "acceptance", "用户", "需求", "故事"]),
    t("Acceptance Criteria", String.raw`\bacceptance criteria\b|验收标准`, "Acceptance criteria，验收标准，说明需求做到什么程度算完成。", prod("PRD 或 ticket 里常写它来减少产品和工程理解偏差。", "产品和项目面试会考察你是否能定义清楚完成条件。"), ["requirement", "QA", "done", "验收", "标准", "需求"]),
    t("Sprint", String.raw`\bsprint\b|迭代周期`, "Sprint，敏捷开发中的短周期迭代。", prod("通常是一到两周，团队会计划、开发、评审和复盘。", "项目经历里常用于说明协作和交付节奏。"), ["agile", "scrum", "backlog", "迭代", "敏捷", "排期"]),
    t("Kanban", String.raw`\bkanban\b|看板`, "Kanban，看板，用列表示任务从待办到完成的流转状态。", prod("常用于可视化任务状态和限制 WIP。", "讲团队协作时可能用它说明项目管理方式。"), ["task", "workflow", "WIP", "看板", "任务", "状态"]),
    t("Design Partner", String.raw`\bdesign partner\b|设计伙伴|共创客户`, "Design partner，深度参与早期产品共创和反馈的客户或伙伴。", prod("产品团队会和他们一起打磨用例和功能范围。", "B2B 早期公司常用 design partner 验证真实需求。"), ["customer", "feedback", "pilot", "客户", "共创", "反馈"]),
    t("Beta", String.raw`\bbeta\b|公测|内测`, "Beta，测试版，产品在正式发布前开放给部分用户使用。", prod("用于收集反馈、发现问题和验证上线风险。", "早期产品常用 beta 招募第一批真实用户。"), ["launch", "feedback", "test", "测试", "公测", "内测"]),
    t("GA", String.raw`\bGA\b|general availability|正式可用`, "General Availability，正式对外可用版本。", prod("从 beta 到 GA 通常意味着稳定性、文档、定价和支持都准备好了。", "GA 可以作为对客户和市场沟通的发布节点。"), ["launch", "release", "beta", "正式", "发布", "可用"], "GA 也可能指 Google Analytics，需要看是否在聊数据分析工具。"),
    t("DAU", String.raw`\bDAU\b|daily active users`, "Daily Active Users，日活跃用户数。", prod("常用于消费产品、社区、工具和 AI 应用的活跃度衡量。", "投资人会结合留存和使用频率判断用户价值。"), ["active", "user", "MAU", "日活", "活跃", "用户"]),
    t("WAU", String.raw`\bWAU\b|weekly active users`, "Weekly Active Users，周活跃用户数。", prod("适合不需要每天使用、但每周有稳定使用习惯的产品。", "可和 DAU、MAU 一起判断使用频率和黏性。"), ["active", "user", "weekly", "周活", "活跃", "用户"]),
    t("MAU", String.raw`\bMAU\b|monthly active users`, "Monthly Active Users，月活跃用户数。", prod("常和 DAU/MAU stickiness 一起看。", "月活只是规模指标，还要结合留存、付费和频率。"), ["active", "user", "DAU", "月活", "活跃", "用户"]),
    t("Stickiness", String.raw`\bstickiness\b|黏性|粘性`, "Stickiness，产品黏性，用户反复回来使用的程度。", prod("常用 DAU/MAU 或留存曲线来近似衡量。", "高黏性通常是产品价值和习惯形成的证据。"), ["DAU", "MAU", "retention", "黏性", "留存", "活跃"]),
    t("Persona", String.raw`\bpersona\b|用户画像`, "Persona，用户画像，对目标用户特征、需求和行为的抽象描述。", prod("用于帮助产品、设计和市场统一理解目标用户。", "和 ICP 不同，persona 更偏用户角色和使用场景。"), ["user", "ICP", "segment", "用户", "画像", "角色"]),
    t("JTBD", String.raw`\bJTBD\b|jobs to be done`, "Jobs To Be Done，用户雇佣产品来完成的真实任务或进步。", prod("常用于从用户目标出发，而不是只看功能清单。", "有助于找到用户愿意切换和付费的核心原因。"), ["job", "pain", "value", "任务", "用户", "痛点"]),
    t("Pain Point", String.raw`\bpain point(s)?\b|痛点`, "Pain point，痛点，用户或客户强烈想解决的问题。", prod("需求判断里会区分真实痛点和轻微不便。", "创业方向常从高频、高痛、高付费意愿的问题开始。"), ["problem", "need", "customer", "痛点", "问题", "需求"]),
    t("Value Prop", String.raw`\bvalue prop\b|value proposition|价值主张`, "Value proposition，价值主张，说明为什么用户应该选择这个产品。", prod("产品和市场会用它统一功能、用户收益和差异化。", "融资和销售里会反复解释 value prop 是否清晰。"), ["positioning", "customer", "benefit", "价值", "主张", "用户收益"]),
    t("Positioning", String.raw`\bpositioning\b|定位`, "Positioning，定位，让目标用户理解你是谁、解决什么问题、和谁不同。", prod("PMM 和产品团队常用它连接功能、市场和竞争格局。", "定位不清会影响销售、融资和增长效率。"), ["PMM", "market", "competitor", "定位", "市场", "竞品"]),
    t("Messaging", String.raw`\bmessaging\b|信息传达|产品话术`, "Messaging，对外表达产品价值的文案、话术和叙事。", prod("常和 positioning、launch、sales enablement 一起出现。", "清晰 messaging 可以降低客户理解成本。"), ["positioning", "copy", "sales", "话术", "文案", "定位"]),
    t("Differentiation", String.raw`\bdifferentiation\b|差异化`, "Differentiation，差异化，说明你和替代方案相比独特在哪里。", prod("产品会从能力、体验、数据、生态或价格上找差异。", "投资人和客户都会问差异化是否能长期保持。"), ["competitor", "moat", "unique", "差异化", "竞品", "护城河"]),
    t("Moat", String.raw`\bmoat\b|护城河`, "Moat，护城河，让竞争对手难以复制或追上的优势。", biz("可能来自网络效应、数据、分发、品牌、成本或生态。", "投资人会看优势是否可持续，而不是短期领先。"), ["defensible", "network effect", "data", "护城河", "优势", "壁垒"]),
    t("Network Effect", String.raw`\bnetwork effect(s)?\b|网络效应`, "Network effect，网络效应，用户越多，产品对每个用户越有价值。", biz("Marketplace、社交、协作和平台型产品常讨论。", "强网络效应可能形成可持续护城河。"), ["marketplace", "platform", "moat", "网络效应", "用户", "平台"]),
    t("RICE", String.raw`\bRICE\b(?=\s+(score|scoring|prioritization|优先级|框架))|reach impact confidence effort`, "RICE，产品优先级框架：Reach、Impact、Confidence、Effort。", prod("适合把功能机会按影响、覆盖人数、置信度和成本排序。", "早期团队可以用它避免只凭直觉排优先级。"), ["priority", "impact", "effort", "优先级", "影响", "成本"], "如果只是普通英文 rice，不应按产品框架理解。"),
    t("RACI", String.raw`\bRACI\b|responsible accountable consulted informed`, "RACI，职责分工矩阵：负责、问责、咨询、知会。", work("跨部门协作里用来明确谁做、谁拍板、谁提供意见、谁只需要同步。", "复杂产品项目可用 RACI 减少责任不清。"), ["owner", "stakeholder", "responsible", "职责", "分工", "拍板"]),

    t("MQL", String.raw`\bMQL\b|marketing qualified lead`, "Marketing Qualified Lead，由市场行为初步判定有潜力的销售线索。", sales("常由内容、广告、活动或下载资料产生。", "市场、增长和销售岗位都会讨论 MQL 到 SQL 的转化。"), ["lead", "marketing", "funnel", "线索", "市场", "转化"]),
    t("SQL", String.raw`\bSQL\b|sales qualified lead`, "Sales Qualified Lead，销售确认值得推进的线索。", sales("销售团队会从 MQL 中筛出 SQL 进入机会推进。", "销售岗位里常和 MQL、opportunity、pipeline 一起出现。"), ["lead", "sales", "MQL", "opportunity", "线索", "销售", "机会"], "SQL 高歧义，销售语境是销售合格线索，技术语境是数据库查询语言。"),
    t("PQL", String.raw`\bPQL\b|product qualified lead`, "Product Qualified Lead，通过产品使用行为判断出来的高意向线索。", sales("PLG 公司常从试用、免费版或产品事件里识别 PQL。", "产品数据会帮助销售判断谁值得跟进。"), ["PLG", "usage", "lead", "试用", "产品使用", "线索"]),
    t("Lead", String.raw`\blead(s)?\b|销售线索|潜在客户`, "Lead，销售线索或潜在客户。", sales("销售漏斗最前端通常从 lead 开始。", "在团队语境里 lead 也可能是负责人或带队的人。"), ["sales", "prospect", "pipeline", "线索", "客户", "销售"], "Lead 也可以是动词或团队负责人，需要结合上下文。"),
    t("Opportunity", String.raw`\bopportunit(y|ies)\b|销售机会|商机`, "Opportunity，进入销售推进阶段的商机。", sales("通常比 lead 更靠后，已经有一定需求、预算或决策路径。", "Pipeline 质量会看 opportunity 的阶段、金额和关闭概率。"), ["pipeline", "deal", "stage", "商机", "销售", "阶段"]),
    t("Quota", String.raw`\bquota\b|销售指标`, "Quota，销售指标，通常是销售人员需要完成的签约或收入目标。", sales("AE、SDR 和销售团队常围绕 quota 规划资源。", "销售岗位 coffee chat 里常问 quota、attainment 和 ramp。"), ["sales", "AE", "target", "销售", "指标", "目标"]),
    t("Discovery Call", String.raw`\bdiscovery call\b|需求发现电话|发现式沟通`, "Discovery call，销售早期用来了解客户需求、痛点和决策流程的沟通。", sales("B2B 销售通常先 discovery，再 demo 或方案推进。", "销售和产品调研都可能借 discovery 了解真实问题。"), ["sales", "pain", "customer", "需求", "痛点", "客户"]),
    t("Demo", String.raw`\bdemo\b|演示`, "Demo，产品演示，向客户、投资人或团队展示功能和价值。", sales("销售 demo 会围绕客户痛点，而不只是逐个展示功能。", "产品 demo 常用于发布、评审或内部对齐。"), ["sales", "product", "customer", "演示", "客户", "功能"]),
    t("Champion", String.raw`\bchampion\b|内部支持者`, "Champion，客户组织内部支持你方案并帮你推进的人。", sales("B2B 销售里 champion 会帮你理解采购、痛点和决策人。", "销售岗位会强调如何识别和培养 champion。"), ["buyer", "sales", "customer", "支持者", "客户", "采购"]),
    t("Economic Buyer", String.raw`\beconomic buyer\b|预算决策人|经济买家`, "Economic buyer，真正掌握预算或最终商业决策的人。", sales("复杂 B2B 销售里要区分使用者、champion 和 economic buyer。", "销售预测会看是否已经接触到预算决策人。"), ["budget", "decision", "buyer", "预算", "决策", "采购"]),
    t("MEDDIC", String.raw`\bMEDDIC\b|MEDDPICC`, "MEDDIC，一套 B2B 企业销售资格评估框架。", sales("常用来确认指标、经济买家、决策标准、痛点和 champion。", "销售岗位面试里可能会问是否熟悉 MEDDIC。"), ["sales", "buyer", "champion", "销售", "采购", "决策"]),
    t("Procurement", String.raw`\bprocurement\b|采购流程|采购部门`, "Procurement，采购或采购流程。", sales("企业销售后期常要经过采购、安全、法务和财务审批。", "采购周期会影响回款、销售周期和 forecast。"), ["legal", "security", "vendor", "采购", "法务", "安全"]),
    t("Renewal", String.raw`\brenewal\b|renew\b|续费`, "Renewal，续费，客户合同到期后继续购买。", sales("CSM 和销售会共同关注续费风险和扩容机会。", "续费质量直接影响 ARR、NRR 和 churn。"), ["CSM", "retention", "contract", "续费", "合同", "留存"]),
    t("Expansion", String.raw`\bexpansion\b|扩容|增购`, "Expansion，老客户扩容或增购。", sales("可能来自更多 seat、更多模块、更高套餐或更多用量。", "高 expansion 会推高 NRR，说明产品在客户内部能继续长大。"), ["NRR", "upsell", "seat", "扩容", "增购", "客户"]),
    t("Upsell", String.raw`\bupsell\b|向上销售|升档`, "Upsell，让现有客户购买更高版本、更大套餐或更多用量。", sales("常和 renewal、expansion、CSM 一起出现。", "产品会设计套餐边界和升级触发点。"), ["expansion", "plan", "pricing", "升档", "套餐", "扩容"]),
    t("Cross-sell", String.raw`\bcross[-\s]?sell\b|交叉销售`, "Cross-sell，向现有客户销售不同产品或模块。", sales("多产品线公司会用 cross-sell 提高客户价值。", "交叉销售能力会影响 LTV 和 NRR。"), ["product", "module", "customer", "交叉销售", "模块", "客户"]),
    t("PLG", String.raw`\bPLG\b|product[-\s]?led growth`, "Product-led growth，产品驱动增长，让用户通过产品体验自然转化和扩散。", sales("常见于免费试用、freemium、自助购买和 PQL。", "增长、产品和销售岗位都会讨论 PLG motion。"), ["product", "PQL", "freemium", "产品驱动", "试用", "自助"]),
    t("SLG", String.raw`\bSLG\b|sales[-\s]?led growth`, "Sales-led growth，销售驱动增长，主要依赖销售团队推进成交。", sales("Enterprise SaaS 常见，销售周期更长但 ACV 可能更高。", "要看 CAC、payback、quota attainment 和 pipeline。"), ["sales", "enterprise", "ACV", "销售驱动", "企业客户", "销售周期"]),
    t("Inbound", String.raw`\binbound\b|入站线索|自然线索`, "Inbound，客户主动找上门或通过内容、搜索、活动进入漏斗。", sales("常和 content、SEO、website、demo request 一起出现。", "增长团队会优化 inbound 的转化路径。"), ["lead", "content", "SEO", "入站", "线索", "内容"]),
    t("Outbound", String.raw`\boutbound\b|外呼|主动开发`, "Outbound，主动触达潜在客户，比如 cold email、电话或 LinkedIn。", sales("早期 B2B 团队常用 outbound 验证 ICP 和话术。", "销售岗位会讨论 outbound motion 和 prospecting。"), ["cold email", "SDR", "prospecting", "主动", "开发", "销售"]),
    t("Cold Email", String.raw`\bcold email\b|冷邮件`, "Cold email，给陌生潜在客户发送的主动开发邮件。", sales("常用于 B2B outbound，目标是获得回复或约 demo。", "networking 里也可能用 cold email 联系校友或从业者。"), ["outbound", "reply", "demo", "冷邮件", "陌生", "开发"]),
    t("RevOps", String.raw`\bRevOps\b|revenue operations`, "Revenue Operations，收入运营，连接销售、市场和客户成功的数据与流程。", sales("负责 pipeline、CRM、forecast、分工和收入流程效率。", "岗位语境里可能是偏系统、流程和数据分析的商业运营角色。"), ["sales", "marketing", "CRM", "收入", "运营", "流程"]),
    t("NPS", String.raw`\bNPS\b|net promoter score`, "Net Promoter Score，净推荐值，用来衡量用户愿不愿意推荐产品。", prod("用户调研和客户成功常用，但不能替代真实留存和行为数据。", "可以作为满意度信号，但要结合样本和用户质量判断。"), ["survey", "customer", "satisfaction", "推荐", "满意度", "调研"]),
    t("CSAT", String.raw`\bCSAT\b|customer satisfaction`, "Customer Satisfaction，客户满意度指标。", prod("常通过问卷或服务后打分收集。", "客服、客户成功和产品体验都会关注 CSAT。"), ["support", "survey", "customer", "满意度", "客户", "客服"]),
    t("QBR", String.raw`\bQBR\b|quarterly business review`, "Quarterly Business Review，季度业务回顾。", sales("客户成功常用 QBR 和大客户复盘价值、用量和下一步。", "业务管理里也可能指团队季度复盘。"), ["quarter", "customer", "review", "季度", "业务回顾", "客户"]),

    t("Embedding", String.raw`\bembedding(s)?\b|向量嵌入|嵌入向量`, "Embedding，把文本、图片等内容表示成向量，方便检索、聚类或相似度计算。", tech("AI 搜索、推荐、RAG 和语义匹配里高频出现。", "AI 应用会用 embedding 做知识库、客服和数据检索。"), ["vector", "RAG", "search", "向量", "检索", "语义"]),
    t("Vector DB", String.raw`\bvector database\b|\bvector DB\b|向量数据库`, "Vector DB，向量数据库，用来存储和检索 embedding。", tech("RAG、语义搜索和推荐系统常用。", "AI infra 或 AI 应用团队会关注召回质量、延迟和成本。"), ["embedding", "RAG", "retrieval", "向量", "数据库", "检索"]),
    t("Inference", String.raw`\binference\b|推理`, "Inference，模型推理，指模型接收输入并生成输出的过程。", tech("AI 产品会关注推理延迟、成本、吞吐和稳定性。", "推理成本会影响毛利率和定价。"), ["latency", "model", "cost", "推理", "模型", "延迟"]),
    t("Latency", String.raw`\blatency\b|延迟|时延`, "Latency，延迟，从请求到响应所花的时间。", tech("实时语音、搜索、AI agent 和协作工具都对延迟敏感。", "低延迟可以成为体验优势，但通常会增加成本或工程复杂度。"), ["realtime", "inference", "response", "延迟", "实时", "响应"]),
    t("Throughput", String.raw`\bthroughput\b|吞吐量`, "Throughput，吞吐量，系统单位时间内能处理多少请求或任务。", tech("AI、数据和后端系统会同时看吞吐、延迟和成本。", "规模化时吞吐影响成本、稳定性和服务能力。"), ["latency", "request", "scale", "吞吐", "请求", "规模"]),
    t("Hallucination", String.raw`\bhallucination(s)?\b|幻觉`, "Hallucination，模型生成看似合理但不真实或无依据的内容。", tech("AI 产品会通过 RAG、引用、评测和 guardrail 降低幻觉。", "如果产品用于高风险场景，幻觉会直接影响可信度和合规。"), ["LLM", "RAG", "grounding", "幻觉", "事实", "引用"]),
    t("Grounding", String.raw`\bgrounding\b|事实锚定|接地`, "Grounding，把模型回答锚定到可验证的资料、上下文或工具结果上。", tech("RAG、引用来源和工具调用都是常见 grounding 方法。", "企业 AI 产品会用 grounding 提高可靠性和可审计性。"), ["RAG", "source", "citation", "事实", "来源", "引用"]),
    t("Prompt", String.raw`\bprompt(s)?\b|提示词`, "Prompt，提示词或输入指令，用来引导模型完成任务。", tech("AI 产品会把 prompt 作为体验、质量和成本的一部分管理。", "聊 AI 工作流时 prompt 可能指日常和模型协作的表达方式。"), ["LLM", "instruction", "system", "提示词", "指令", "模型"]),
    t("Fine-tuning", String.raw`\bfine[-\s]?tuning\b|微调`, "Fine-tuning，微调，用特定数据继续训练模型以适配任务或风格。", tech("通常和 RAG、prompt、eval 比较，选择成本和效果更合适的方案。", "AI 团队会看数据质量、评测收益和维护成本。"), ["model", "data", "SFT", "微调", "模型", "数据"]),
    t("SFT", String.raw`\bSFT\b|supervised fine[-\s]?tuning`, "Supervised Fine-Tuning，监督微调，用标注样例训练模型按目标方式回答。", tech("适合有稳定任务和高质量示例数据的场景。", "需要权衡标注成本、模型效果和上线维护。"), ["fine-tuning", "data", "label", "监督", "微调", "标注"]),
    t("RLHF", String.raw`\bRLHF\b|reinforcement learning from human feedback`, "Reinforcement Learning from Human Feedback，基于人类反馈的强化学习。", tech("常用于让模型更符合人类偏好和安全要求。", "大模型公司或深度 AI infra 团队会更常讨论。"), ["preference", "feedback", "model", "反馈", "偏好", "强化学习"]),
    t("LoRA", String.raw`\bLoRA\b|low[-\s]?rank adaptation`, "Low-Rank Adaptation，一种参数高效微调方法。", tech("用于较低成本适配模型能力或风格。", "AI 团队会在成本、效果和部署复杂度之间做取舍。"), ["fine-tuning", "adapter", "model", "微调", "低秩", "模型"], "", ""),
    t("VLM", String.raw`\bVLM\b|vision[-\s]?language model`, "Vision-Language Model，视觉语言模型，能同时理解图像和文本。", tech("常用于图片理解、文档解析、质检、OCR 后处理和多模态助手。", "多模态 AI 产品会讨论 VLM 的准确率、成本和延迟。"), ["vision", "image", "OCR", "视觉", "图像", "多模态"]),
    t("OCR", String.raw`\bOCR\b|optical character recognition`, "Optical Character Recognition，文字识别，把图片或扫描件中的文字提取出来。", tech("文档处理、票据、合同、截图理解里常见。", "AI 产品可能把 OCR 和 VLM、RAG 组合起来。"), ["document", "image", "scan", "文字识别", "图片", "文档"]),
    t("ASR", String.raw`\bASR\b|automatic speech recognition`, "Automatic Speech Recognition，自动语音识别，把语音转成文字。", tech("实时转写、会议助手、字幕和语音输入都依赖 ASR。", "本项目里的 SenseVoice 和 Whisper 都是 ASR 方向的模型或方案。"), ["speech", "transcribe", "voice", "语音", "转写", "识别"]),
    t("TTS", String.raw`\bTTS\b|text[-\s]?to[-\s]?speech`, "Text-to-Speech，文本转语音。", tech("语音助手、有声内容和客服场景常用。", "AI 语音产品会同时关注 TTS 的自然度、延迟和成本。"), ["voice", "speech", "audio", "语音", "音频", "合成"]),
    t("STT", String.raw`\bSTT\b|speech[-\s]?to[-\s]?text`, "Speech-to-Text，语音转文字，和 ASR 基本同义。", tech("实时字幕、会议记录和语音输入常用这个说法。", "如果对方说 STT，多半是在讲语音识别能力或供应商。"), ["ASR", "transcribe", "speech", "语音", "转写", "字幕"]),
    t("Agent", String.raw`\bagent(s)?\b|智能体`, "Agent，能根据目标调用工具、记忆或多步规划来完成任务的 AI 系统。", tech("AI agent 常和 tool calling、workflow、automation 一起出现。", "Agent 产品要特别关注可靠性、权限、成本和人类接管。"), ["tool", "workflow", "automation", "智能体", "工具", "自动化"], "Agent 也可能只是客服坐席或销售代表，需要看是否在 AI 语境。"),
    t("Human-in-the-loop", String.raw`\bhuman[-\s]?in[-\s]?the[-\s]?loop\b|\bHITL\b|人在回路`, "Human-in-the-loop，人在回路，让人类参与审核、纠错或关键决策。", tech("高风险 AI 工作流常保留人工确认。", "可以先用人工兜底提升可靠性，再逐步自动化。"), ["review", "approval", "AI", "人工", "审核", "确认"]),
    t("Observability", String.raw`\bobservability\b|可观测性`, "Observability，可观测性，通过日志、指标和追踪理解系统运行状态。", tech("AI 产品也需要看 prompt、模型输出、延迟、成本和错误。", "可靠性和排障能力会影响企业客户信任。"), ["logs", "metrics", "tracing", "可观测", "日志", "指标"]),
    t("Telemetry", String.raw`\btelemetry\b|遥测|埋点数据`, "Telemetry，产品或系统自动上报的使用和运行数据。", tech("常用于分析用户行为、性能和异常。", "早期产品会用 telemetry 找到真实使用情况和留存信号。"), ["analytics", "event", "usage", "埋点", "数据", "使用"]),
    t("Benchmark", String.raw`\bbenchmark(s)?\b|基准测试`, "Benchmark，基准测试，用统一任务或指标比较模型、产品或系统表现。", tech("AI 和工程团队会用 benchmark 做模型选择和回归测试。", "也可能指和同行公司或市场指标做比较。"), ["eval", "metric", "compare", "基准", "评测", "指标"]),
    t("Eval", String.raw`\beval(s)?\b|evaluation\b|评测`, "Eval，评测，用固定样本和指标判断模型或系统表现。", tech("AI 团队会用 eval 比较模型、prompt、检索策略和安全策略。", "创业团队应把 eval 当作产品质量的一部分，而不是只靠主观感觉。"), ["benchmark", "metric", "model", "评测", "指标", "模型"]),
    t("MLOps", String.raw`\bMLOps\b|machine learning operations`, "MLOps，机器学习工程运营，覆盖模型训练、部署、监控和迭代。", tech("AI 产品上线后需要 MLOps 保证质量和稳定性。", "团队会在自建和托管平台之间权衡成本和速度。"), ["model", "deployment", "monitoring", "模型", "部署", "监控"]),
    t("LLMOps", String.raw`\bLLMOps\b|LLM operations`, "LLMOps，大语言模型应用的运营和工程实践。", tech("包括 prompt、评测、监控、成本、版本和安全策略管理。", "AI 应用团队会用它保证 LLM 产品持续可控。"), ["LLM", "eval", "monitoring", "大模型", "评测", "监控"]),
    t("SLA", String.raw`\bSLA\b|service level agreement`, "Service Level Agreement，服务等级协议，对可用性、响应时间等作出承诺。", tech("企业客户常会在合同里要求 SLA。", "SLA 会影响架构、运维、客服和赔付条款。"), ["uptime", "contract", "support", "服务等级", "可用性", "合同"]),
    t("SLO", String.raw`\bSLO\b|service level objective`, "Service Level Objective，服务等级目标，团队内部追踪的可靠性目标。", tech("通常比 SLA 更偏内部运营和工程质量管理。", "SLO 帮助团队在速度和可靠性之间做取舍。"), ["SLA", "reliability", "uptime", "可靠性", "目标", "可用性"]),
    t("SLI", String.raw`\bSLI\b|service level indicator`, "Service Level Indicator，服务等级指标，用来衡量 SLO 是否达成。", tech("常见 SLI 包括延迟、错误率、可用性和吞吐。", "定义好 SLI 才能监控可靠性，而不是凭感觉。"), ["SLO", "latency", "error rate", "指标", "延迟", "错误率"]),
    t("Webhook", String.raw`\bwebhook(s)?\b|回调`, "Webhook，事件发生时由一个系统主动通知另一个系统的回调机制。", tech("SaaS 集成、支付、自动化和通知场景常见。", "开放 webhook 可以提升平台化和生态集成能力。"), ["integration", "event", "API", "回调", "事件", "集成"]),
    t("OAuth", String.raw`\bOAuth\b|open authorization`, "OAuth，开放授权协议，用于让第三方应用在不拿到密码的情况下访问资源。", tech("登录、授权、第三方集成和 API 平台常见。", "企业客户会关注授权安全、权限范围和审计。"), ["auth", "token", "integration", "授权", "登录", "令牌"], "", ""),
    t("SSO", String.raw`\bSSO\b|single sign[-\s]?on`, "Single Sign-On，单点登录，让用户用一个身份系统登录多个应用。", tech("企业 SaaS 常把 SSO 当作高级版或企业版能力。", "支持 SSO 有助于进入更大客户，但实现和合规成本更高。"), ["enterprise", "auth", "login", "单点登录", "企业", "身份"]),
    t("RBAC", String.raw`\bRBAC\b|role[-\s]?based access control`, "Role-Based Access Control，基于角色的权限控制。", tech("企业产品常需要管理员、成员、访客等角色权限。", "B2B SaaS 做到团队协作后通常会补 RBAC。"), ["permission", "role", "admin", "权限", "角色", "管理员"]),
    t("SOC 2", String.raw`\bSOC\s*2\b|SOC II|system and organization controls`, "SOC 2，一种常见的信息安全和控制审计报告。", tech("企业客户采购软件时经常会要求安全和合规证明。", "拿 SOC 2 会增加销售可信度，但也需要流程和审计投入。"), ["security", "compliance", "audit", "安全", "合规", "审计"]),
    t("GDPR", String.raw`\bGDPR\b|general data protection regulation`, "GDPR，欧盟通用数据保护条例。", tech("涉及欧盟用户数据时需要关注隐私、同意、删除和数据处理。", "出海 SaaS 或数据产品常会被客户问到 GDPR。"), ["privacy", "data", "EU", "隐私", "数据", "欧盟"]),
    t("HIPAA", String.raw`\bHIPAA\b|health insurance portability and accountability act`, "HIPAA，美国医疗健康数据相关的隐私和安全合规要求。", tech("医疗、保险和健康科技产品需要特别关注。", "进入 healthcare 客户时常会被问是否 HIPAA compliant。"), ["healthcare", "privacy", "data", "医疗", "隐私", "健康"]),
    t("ETL", String.raw`\bETL\b|extract transform load`, "ETL，先抽取和转换数据，再加载到目标系统。", tech("数据平台、BI 和数据仓库里常见。", "如果团队做数据产品，ETL 会影响数据质量和时效。"), ["data", "warehouse", "pipeline", "数据", "抽取", "转换"]),
    t("ELT", String.raw`\bELT\b|extract load transform`, "ELT，先加载数据，再在目标系统里转换。", tech("现代数据栈里常和云数仓、dbt 一起出现。", "适合数据量大、转换逻辑需要在仓库里管理的场景。"), ["data", "warehouse", "dbt", "数据", "加载", "转换"]),
    t("Data Warehouse", String.raw`\bdata warehouse\b|数据仓库|数仓`, "Data warehouse，数据仓库，用来集中存储和分析结构化业务数据。", tech("BI、报表、数据分析和 AI 数据基础设施都会依赖它。", "公司增长后会用数仓统一指标口径。"), ["BI", "analytics", "ETL", "数据仓库", "数仓", "指标"]),
    t("Lakehouse", String.raw`\blakehouse\b|湖仓`, "Lakehouse，湖仓，把数据湖的灵活性和数仓的治理能力结合起来。", tech("数据平台和 AI infra 讨论里常出现。", "适合数据类型复杂、分析和机器学习都要支持的场景。"), ["data lake", "warehouse", "analytics", "湖仓", "数据湖", "数仓"]),
    t("PII", String.raw`\bPII\b|personally identifiable information`, "Personally Identifiable Information，个人可识别信息。", tech("隐私、合规、安全和数据处理讨论中高频出现。", "处理 PII 需要权限、脱敏、保留周期和审计。"), ["privacy", "data", "security", "隐私", "个人信息", "脱敏"]),
    t("DPA", String.raw`\bDPA\b|data processing agreement`, "Data Processing Agreement，数据处理协议。", tech("企业客户和供应商签约时常见，尤其涉及个人数据。", "出海或卖给大客户时，DPA 是采购和法务常问的材料。"), ["privacy", "legal", "GDPR", "数据处理", "协议", "隐私"], "DPA 也可能有其他含义，合规和合同语境下多半是数据处理协议。"),
    t("API Gateway", String.raw`\bAPI gateway\b|API网关`, "API Gateway，API 网关，用来统一管理路由、鉴权、限流和监控。", tech("平台型产品和微服务架构常见。", "企业客户会关注 API 稳定性、权限和安全。"), ["API", "auth", "rate limit", "网关", "鉴权", "限流"]),
    t("Rate Limit", String.raw`\brate limit\b|限流`, "Rate limit，限流，限制单位时间内的请求数量。", tech("API、AI 推理和平台服务都会用它保护系统稳定。", "商业化时也可能用限流区分套餐和用量。"), ["API", "quota", "request", "限流", "请求", "套餐"]),

    t("Behavioral", String.raw`\bbehavioral\b|behavioral interview|行为面试`, "Behavioral interview，行为面试，用过去经历判断能力和合作方式。", work("常让你讲冲突、失败、领导力、影响力和取舍。", "产品岗位也会用 behavioral 看跨职能协作和判断力。"), ["interview", "STAR", "story", "面试", "经历", "行为"]),
    t("Case Study", String.raw`\bcase study\b|case interview|案例面试`, "Case study，案例题或案例研究，用真实或模拟问题考察分析和表达。", work("咨询、产品、运营和增长岗位常见。", "产品 case 常看用户问题、指标、方案和 tradeoff。"), ["interview", "analysis", "problem", "案例", "面试", "分析"]),
    t("Take-home", String.raw`\btake[-\s]?home\b|homework assignment|作业题`, "Take-home，带回家完成的面试作业或项目题。", work("公司用它看实际产出，但也要注意投入时间是否合理。", "产品 take-home 可能要求写 PRD、分析指标或设计方案。"), ["interview", "assignment", "homework", "作业", "面试", "项目"]),
    t("HM", String.raw`\bHM\b|hiring manager`, "Hiring Manager，招聘经理，通常是最终加入后会管理你或负责这个岗位的人。", work("和 HM 聊时重点是岗位预期、团队问题、成功标准和合作方式。", "产品岗位 HM 可能重点看产品判断和跨职能影响力。"), ["interview", "team", "role", "招聘", "经理", "岗位"]),
    t("Recruiter Screen", String.raw`\brecruiter screen\b|HR screen|recruiter call|招聘初筛`, "Recruiter screen，招聘初筛，通常确认背景、动机、薪资范围和流程。", work("这是进入正式面试前的第一道沟通。", "产品岗位也会先筛选经历是否和岗位匹配。"), ["interview", "recruiter", "comp", "招聘", "初筛", "流程"]),
    t("Loop", String.raw`\binterview loop\b|\bloop\b(?=\s+(interview|round|面试))|面试轮`, "Interview loop，一整套正式面试轮次。", work("通常包括 HM、同事、跨职能、behavioral 和专业面。", "产品岗位 loop 可能包含 product sense、execution、leadership 等。"), ["interview", "round", "onsite", "面试", "轮次", "流程"]),
    t("Debrief", String.raw`\bdebrief\b|面试复盘|复盘会`, "Debrief，面试或项目后的复盘讨论。", work("招聘流程里指面试官汇总反馈并做决定。", "项目里也指复盘发生了什么、学到了什么和下一步。"), ["feedback", "interview", "review", "复盘", "反馈", "面试"]),
    t("Leveling", String.raw`\bleveling\b|定级|职级评估`, "Leveling，定级，判断候选人或员工对应哪个职级。", work("会影响薪酬、职责范围、预期影响力和晋升路径。", "产品岗位定级常看 scope、impact、ambiguity 和 leadership。"), ["level", "scope", "comp", "定级", "职级", "薪酬"]),
    t("Comp", String.raw`\bcomp\b|compensation|薪酬包`, "Compensation，薪酬包，通常包含 base、bonus、equity 等。", work("聊 offer 时 comp 是核心问题之一。", "公司成本和股权激励里也会出现 compensation。"), ["salary", "bonus", "equity", "薪酬", "工资", "奖金"]),
    t("TC", String.raw`\bTC\b|total compensation`, "Total Compensation，总薪酬，通常包含 base、bonus 和 equity 的年化价值。", work("求职谈薪时常问 TC，而不只是 base salary。", "股权价值、vesting 和 refresh 会影响实际 TC。"), ["base", "bonus", "equity", "总包", "薪酬", "股票"]),
    t("Equity", String.raw`\bequity\b|股权|期权`, "Equity，股权或期权，是薪酬和创业融资中的所有权权益。", work("offer 里要看数量、行权价、vesting、cliff 和公司阶段。", "创始人、员工和投资人的 equity 会出现在 cap table 里。"), ["vesting", "cliff", "cap table", "股权", "期权", "归属"]),
    t("Vesting", String.raw`\bvesting\b|归属期`, "Vesting，股权或期权逐步归属的安排。", work("常见是四年 vesting、一年 cliff。", "创始人和员工股权都会设置 vesting 来绑定长期贡献。"), ["equity", "cliff", "option", "归属", "股权", "期权"]),
    t("Cliff", String.raw`\bcliff\b|一年 cliff|归属悬崖`, "Cliff，归属悬崖期，通常满一定时间后才开始一次性归属一部分权益。", work("常见 offer 里是一年 cliff，未满一年离开可能没有股权归属。", "创始人股权 vesting 也常设置 cliff。"), ["vesting", "equity", "year", "归属", "股权", "一年"]),
    t("Referral", String.raw`\breferral\b|内推|推荐`, "Referral，内推或推荐，通过熟人把你推荐给招聘或团队。", work("coffee chat 后常见下一步是问对方是否愿意 referral。", "创业公司招聘也常依赖 referral 找高质量候选人。"), ["networking", "recruiter", "resume", "内推", "推荐", "简历"]),
    t("STAR", String.raw`\bSTAR\b|situation task action result`, "STAR，行为面试答题结构：情境、任务、行动、结果。", work("用来组织经历故事，避免回答太散。", "产品面试讲项目经历时也可以用 STAR 强化结构。"), ["behavioral", "interview", "story", "面试", "经历", "结果"]),
    t("Scope", String.raw`\bscope\b|范围|职责范围`, "Scope，范围，可以指项目范围、职责范围或职级影响范围。", work("定级和晋升里常用 scope 判断你负责事情的复杂度和影响面。", "产品项目里 scope 决定这次做什么、不做什么。"), ["impact", "level", "project", "范围", "职责", "项目"]),
    t("Impact", String.raw`\bimpact\b|影响力|业务影响`, "Impact，影响或业务结果，说明你的工作带来了什么可观察变化。", work("面试和绩效里会追问你的个人贡献和结果指标。", "产品工作会把 shipped feature 和业务或用户指标连接起来。"), ["metric", "result", "scope", "影响", "结果", "指标"]),
    t("Promo", String.raw`\bpromo\b|promotion|晋升`, "Promotion，晋升，从当前职级升到更高职级。", work("常和 scope、impact、calibration、manager support 一起讨论。", "产品岗位晋升通常需要证明更大范围和更高影响力。"), ["level", "impact", "manager", "晋升", "职级", "影响力"]),
    t("1:1", String.raw`\b1[:：]1\b|one[-\s]?on[-\s]?one|一对一`, "1:1，一对一沟通，通常是和经理、同事或 networking 对象单独聊。", work("coffee chat 本身也可以被称为 informal 1:1。", "团队管理和跨职能协作中常用 1:1 对齐问题。"), ["manager", "chat", "sync", "一对一", "沟通", "经理"]),
    t("EOD", String.raw`\bEOD\b|end of day`, "End of Day，今天结束前或当天晚些时候。", work("职场沟通里常见时间承诺，比如 send it by EOD。", "项目协作里用来说明截止时间。"), ["deadline", "today", "send", "今天", "下班前", "截止"], "跨时区时 EOD 需要确认对方时区。"),
    t("ETA", String.raw`\bETA\b|estimated time of arrival`, "Estimated Time of Arrival，预计完成或到达时间。", work("职场协作里常问某件事什么时候能好。", "项目排期和发布沟通中常用 ETA。"), ["timeline", "deadline", "ship", "预计", "时间", "完成"]),
    t("FYI", String.raw`\bFYI\b|for your information`, "For Your Information，供你参考或通知你一下。", work("常用于邮件、Slack 和异步沟通，通常不一定要求行动。", "项目更新里用 FYI 表示同步信息。"), ["email", "update", "note", "供参考", "同步", "通知"]),
    t("OOO", String.raw`\bOOO\b|out of office`, "Out of Office，不在办公室或休假中。", work("邮件和日历里常见，表示对方暂时无法及时回复。", "项目排期里要考虑关键成员 OOO。"), ["vacation", "away", "calendar", "休假", "不在", "日历"]),
    t("WFH", String.raw`\bWFH\b|work from home`, "Work From Home，在家办公。", work("聊工作方式、团队文化和远程政策时常见。", "分布式团队协作里会和 async、remote 一起出现。"), ["remote", "office", "hybrid", "在家办公", "远程", "办公室"]),
    t("Async", String.raw`\basync\b|asynchronous|异步沟通`, "Async，异步沟通，不要求双方同时在线。", work("远程团队常强调 async writing 和文档化。", "项目协作里 async 可以减少会议，但要求表达更清楚。"), ["remote", "doc", "Slack", "异步", "文档", "远程"]),
    t("TL;DR", String.raw`\bTL;?DR\b|too long didn'?t read|太长不看`, "Too Long; Didn't Read，长内容前的简短摘要。", work("邮件、文档和项目更新里常用来帮读者快速抓重点。", "PRD 或决策文档中 TL;DR 可以先给结论。"), ["summary", "doc", "email", "摘要", "结论", "文档"]),
    t("Action Item", String.raw`\baction item(s)?\b|\bAI\b(?=\s*(?:列表|事项|跟进))|行动项`, "Action item，行动项，会后需要明确谁来做、做什么、什么时候完成。", work("会议后常用 action items 收束下一步。", "项目协作里 action item 需要 owner 和 deadline。"), ["owner", "deadline", "next step", "行动项", "负责人", "截止"], "AI 在大多数语境是人工智能；只有明确跟事项相关时才按 action item。"),
    t("Blocker", String.raw`\bblocker(s)?\b|阻塞项|卡点`, "Blocker，阻塞项，正在阻止事情继续推进的问题。", work("项目沟通里常问 blockers，意思是有什么卡住你。", "跨职能项目需要尽快暴露和清理 blocker。"), ["risk", "dependency", "blocked", "阻塞", "卡点", "依赖"]),
    t("Warm Intro", String.raw`\bwarm intro\b|warm introduction|熟人介绍`, "Warm intro，熟人介绍，通过共同联系人引荐。", work("coffee chat、求职和融资 networking 里非常常见。", "创业者找投资人时 warm intro 通常比冷邮件更有效。"), ["referral", "network", "investor", "介绍", "熟人", "内推"]),
    t("Informational Interview", String.raw`\binformational interview\b|信息访谈`, "Informational interview，信息访谈，主要为了了解行业、公司或岗位，而不是正式面试。", work("Coffee chat 很多时候就是轻量的信息访谈。", "也可用于了解市场、用户和从业者观点。"), ["coffee chat", "networking", "career", "信息访谈", "了解", "行业"]),
    t("Skip-level", String.raw`\bskip[-\s]?level\b|隔级`, "Skip-level，和直属经理的上级进行的沟通。", work("大公司里常见，用来了解团队方向、反馈和职业发展。", "管理和组织协作里也会讨论 skip-level 反馈。"), ["manager", "leadership", "feedback", "隔级", "经理", "反馈"]),
    t("Manager Track", String.raw`\bmanager track\b|管理线`, "Manager track，管理线职业路径，和 IC track 相对。", work("职业发展里常讨论要走 IC 还是 manager track。", "产品组织里也会区分个人贡献和带团队。"), ["IC", "career", "leadership", "管理线", "职业", "团队"]),
  ];
})();
